### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeppojeps**
added step-by-step

### CODE REVIEW

**Comment by badumbatish** [comment]
perhaps we should also add a pipeline as proof of sucess for installation

**Comment by jeppojeps** [comment]
OK will add an action for that to check that the entire pipeline works, would you recommend to modify an existing action perhaps?

**Comment by badumbatish** [comment]
Its a bit unclear if getting the bindings requires cmake building of the the repo or not, if it does you can add it to cmake multi platform, but if not I think a dedicated ci would save us more time in the long run

**Review by badumbatish — APPROVED** [review]

**Comment by badumbatish** [comment]
python installer ci is added, I'll merge this pr

**Pull request merged**
